[package]
name = "aldebaran-id"
version = "0.1.0"
edition = "2024"

[features]
default = []

[dependencies]
tokel = "0.2.5"
aldebaran-dsa = { version = "0.1.0", path = "../aldebaran-dsa" }
aldebaran-hash = { version = "0.1.0", path = "../aldebaran-hash" }
aldebaran-heap = { version = "0.1.0", path = "../aldebaran-heap" }
aldebaran-primitive = { version = "0.1.0", path = "../aldebaran-primitive" }
