[package]
name = "aldebaran"
version = "0.1.0"
description = "Compiler framework for source processing, parsing, diagnostics, and supporting infrastructure"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/aldebaran"
edition = "2024"

[features]
default = []
report-codegen = ["aldebaran-report/codegen"]

[[test]]
name = "report_codegen"
required-features = ["report-codegen"]



[dependencies]
aldebaran-ansi.workspace = true
aldebaran-dsa.workspace = true
aldebaran-grammar.workspace = true
aldebaran-hash.workspace = true
aldebaran-heap.workspace = true
aldebaran-ice.workspace = true
aldebaran-id.workspace = true
aldebaran-interner.workspace = true
aldebaran-logic.workspace = true
aldebaran-primitive.workspace = true
aldebaran-print.workspace = true
aldebaran-report.workspace = true
aldebaran-source.workspace = true
aldebaran-span.workspace = true
aldebaran-style.workspace = true
aldebaran-text.workspace = true
aldebaran-visualize.workspace = true
