[package]
name = "aldebaran-examples"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
aldebaran = { workspace = true, features = ["report-codegen"] }
aldebaran-ansi.workspace = true
aldebaran-dsa.workspace = true
aldebaran-grammar.workspace = true
aldebaran-hash.workspace = true
aldebaran-heap.workspace = true
aldebaran-ice.workspace = true
aldebaran-id.workspace = true
aldebaran-interner.workspace = true
aldebaran-logic.workspace = true
aldebaran-primitive.workspace = true
aldebaran-print.workspace = true
aldebaran-report = { workspace = true, features = ["codegen"] }
aldebaran-source.workspace = true
aldebaran-span.workspace = true
aldebaran-style.workspace = true
aldebaran-text.workspace = true
aldebaran-visualize.workspace = true
