[package]
name = "aldebaran-dsa"
version = "0.1.0"
description = "Data structures and algorithms for Aldebaran compiler infrastructure"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/aldebaran-dsa"
edition = "2024"

[features]
default = ["profile"]
profile = []

[dependencies]
tokel.workspace = true
hashbrown.workspace = true
smallvec.workspace = true
aldebaran-primitive.workspace = true
