[package]
name = "aldebaran-text"
version = "0.1.0"
description = "Lexical scanning and text processing for Aldebaran"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/aldebaran-text"
edition = "2024"


[dependencies]
aldebaran-grammar.workspace = true
aldebaran-ice.workspace = true
aldebaran-logic.workspace = true
aldebaran-print.workspace = true
aldebaran-report.workspace = true
aldebaran-dsa.workspace = true
aldebaran-id.workspace = true
aldebaran-primitive.workspace = true
aldebaran-hash.workspace = true
aldebaran-source.workspace = true
aldebaran-span.workspace = true
aldebaran-visualize.workspace = true
aldebaran-interner.workspace = true
