[package]
name = "aldebaran-text"
description = "Text processing for Aldebaran"
version = "0.1.0"
edition = "2024"


[dependencies]
aldebaran-grammar.workspace = true
aldebaran-ice.workspace = true
aldebaran-logic.workspace = true
aldebaran-print.workspace = true
aldebaran-report.workspace = true
aldebaran-dsa.workspace = true
aldebaran-id.workspace = true
aldebaran-primitive.workspace = true
aldebaran-hash.workspace = true
aldebaran-source.workspace = true
aldebaran-span.workspace = true
aldebaran-visualize.workspace = true
aldebaran-interner.workspace = true
