[package]
name = "aldebaran-report"
version = "0.1.0"
description = "Allocation-free diagnostic reports and source annotations"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/aldebaran-report"
edition = "2024"

[features]
default = []
codegen = ["dep:aldebaran-report-macro"]

[dependencies]
aldebaran-report-macro = { workspace = true, optional = true }
aldebaran-ansi.workspace = true
aldebaran-dsa.workspace = true
aldebaran-logic.workspace = true
aldebaran-primitive.workspace = true
aldebaran-print.workspace = true
aldebaran-source.workspace = true
aldebaran-span.workspace = true
aldebaran-visualize.workspace = true
