[package]
name = "aldebaran-report-macro"
version = "0.1.0"
description = "Procedural derive macro for Aldebaran diagnostic reports"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/aldebaran-report-macro"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
proc-macro-crate.workspace = true
quote.workspace = true
aldebaran-report-codegen.workspace = true
syn.workspace = true
