[package]
name = "aldebaran-hash"
version = "0.1.0"
description = "Hash function integrations used by Aldebaran"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/aldebaran-hash"
edition = "2024"

[dependencies]
ahash.workspace = true
fnv.workspace = true
rustc-hash.workspace = true
